spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finance-manager
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  expiration: 134353
  secret: 123456
