spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
  server:
    servlet:
      context-path: /finance-manager/api
  jwt:
    expiration: ${JWT_EXPIRATION}
    secret: ${JWT_SECRET}
